language: scala
jdk:
  - oraclejdk8
before_script: ./make_credentials.sh
script: 
  - sbt ^test ^publishLocal ^scripted
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -Rf $HOME/.ivy2/cache/scala_2.10/sbt_0.13/io.gatling/
  - rm -Rf $HOME/.ivy2/cache/scala_2.12/sbt_1.0/io.gatling/

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

# whitelist
branches:
  only:
    - master
